// <auto-generated />
using demomvc.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;

namespace demomvc.Migrations
{
    [DbContext(typeof(MvcContext))]
    [Migration("20181027045618_m1")]
    partial class m1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("demomvc.Models.Factura", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodigoCarga");

                    b.Property<string>("CodigoConductor");

                    b.Property<string>("CodigoFactura")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("Destino");

                    b.Property<string>("Estado");

                    b.Property<string>("FechaCobrado");

                    b.Property<string>("FechaDestino");

                    b.Property<string>("FechaEntregaDocumento");

                    b.Property<string>("FechaSalida");

                    b.Property<string>("MontoCobrado");

                    b.Property<string>("MontoFacturado");

                    b.Property<string>("Origen");

                    b.Property<string>("PlacaCarreta");

                    b.Property<string>("PlacaTracto");

                    b.HasKey("ID");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("demomvc.Models.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellidos");

                    b.Property<string>("Celular");

                    b.Property<string>("Contraseña");

                    b.Property<string>("Correo");

                    b.Property<string>("Nacimiento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("Usu");

                    b.HasKey("ID");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
